### ISSUE TITLE
Refresh required to see the new state after toggling

### ISSUE THREAD

**Issue by daveyheuser** [wKovacs64/gatsby-plugin-use-dark-mode#24] opened 2019-08-11 21:22 UTC
I'm toggling between the different appearances with the following code:
```
<button onClick={useDarkMode().toggle}>Toggle dark mode</button>
```

I also load in the script as such:
```
import useDarkMode from 'use-dark-mode'
```

To me this looks fine, but for some reason I have to refresh my browser to see the new state whilst the demo here works just fine without the need to refresh: https://codesandbox.io/s/mzj64x80ny 

I get no errors in the console, so I'm not quite sure how to debug this either.

**Comment by wKovacs64** [comment] 2019-08-11 22:23
Hi @daveyheuser!

I'd probably need to see more than that to help you debug (can you reproduce it in a CodeSandbox?). Also, just to be clear, all this plugin (`gatsby-plugin-use-dark-mode`) does is inject the no-flash script at the top of `<body>` in a Gatsby project. All the actual dark mode stuff is handled by `use-dark-mode` itself. You are using Gatsby, yes?

Here is a Gatsby example of it working as expected: https://codesandbox.io/s/gatsby-plugin-use-dark-mode-tzz2q

---

#### Side note:

You typically don't want to call a hook that way. Rather, you'll want to invoke it once and then use the properties of the return value in your rendered elements:

```js
const darkMode = useDarkMode();

return (
  <button onClick={darkMode.toggle}>Toggle dark mode</button>
);
```

In this particular case, it might not matter since every invocation of the hook will be using the same `localStorage` key to store the value, so it will happen to work, but that won't always be the case.

**Comment by daveyheuser** [comment] 2019-08-12 18:58
Thanks for getting back to this so quickly! I managed to fix it just now by removing the options and clearing the site's data (rookie mistake). It looks like the options don't work as toggling between dark / light is toggling the default classes of the library as opposed to the options being defined in the Gatsby plugin. 

I'll also look into the way you're suggesting of calling the hook, thanks for that!

**Comment by wKovacs64** [comment] 2019-08-12 20:35
Hey, glad to hear you got it working! In the [Advanced Configuration](https://github.com/wKovacs64/gatsby-plugin-use-dark-mode#advanced-configuration) section of the readme, I mention at the bottom that you will need to specify the options in both the plugin configuration as well as your usage of the hook as they are separate and currently have no way to communicate.

For example, configuring the plugin like so:

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-use-dark-mode',
      options: {
        classNameDark: 'dark',
        classNameLight: 'light',
      },
    },
  ],
};
```

...would require the following usage of the hook:

```js
const darkMode = useDarkMode(false, {
  classNameDark: 'dark',   // These have to match
  classNameLight: 'light', // the plugin config. :\
});
```

It's a bit clunky, unfortunately. Is that what you ran into, or are you already doing this and something still isn't working?

**Comment by wKovacs64** [comment] 2019-08-20 22:06
Closing, but let me know if there are any outstanding issues.

**Closed by wKovacs64** 2019-08-20 22:06 UTC
